version: '3'
services:
  grafana:
    image: ixendrax/telegraf-influxdb-grafana:latest
    container_name: grafana
    environment:
      TZ: Europe/London
    restart: unless-stopped
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
      - /volume1/docker/grafana/influxdb:/var/lib/influxdb
    ports:
      - 3003:3003
      - 5144:514/udp
