version: '3'
services:
  grafana:
    image: ghcr.io/ixendrax/syn-nas-dashboard:main
    container_name: grafana
    environment:
      TZ: Australia/Sydney
    restart: unless-stopped
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
      - /volume1/docker/influxdb:/var/lib/influxdb
    ports:
      - 3003:3003
      - 5144:514/udp
